#!/usr/bin/env bash

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

APP="$1"

function execute_hooks() {
  local hooks_path="$1"

  echo $hooks_path

  if ! dokku enter $APP web test -f $hooks_path; then
    echo "       $hooks_path not found or executable bit not set. Skipping ..."
    exit 0
  fi
  echo "       $hooks_path file found. Running it ..."
  dokku enter $APP web $hooks_path
}
